app:
  allowed: # 允许无需验证可以直接访问的 主机 或 ip地址 满足一项即可
    hosts: localhost,127.0.0.1
    ips: 127.0.0.1
spring:
  application:
    name: application.yml
  profiles:
    active: dev  # 默认激活开发环境
  thymeleaf: # Thymeleaf设置
    prefix: classpath:/views/
    suffix: .html
  freemarker:
    enabled: false # 禁止自动装配freemarker
  web:
    resources:
      add-mappings: false
server:
  port: 8899
  servlet:
    context-path: / # 整个项目的前缀
--- # pro 生产配置
spring:
  config:
    activate:
      on-profile: pro  # 开发环境配置
  thymeleaf:
    cache: true
--- # dev 开发配置
spring:
  config:
    activate:
      on-profile: dev  # 开发环境配置
  thymeleaf:
    cache: false